### ISSUE TITLE
Maybe users are sharing the same session

### ISSUE THREAD

**Issue by brenopolanski** [brenopolanski/coffee-club#24]
See these files:
- https://github.com/brenopolanski/coffee-club/blob/master/server.js#L21
- https://github.com/brenopolanski/coffee-club/blob/master/controllers/home.js#L48

**Comment by thiagoss** [comment]
Perhaps the token should be per session?
https://github.com/brenopolanski/coffee-club/blob/master/controllers/auth.js#L17

**Comment by brenopolanski** [comment]
yup @thiagoss :+1: 

**app.token** is global.. rsrsrsr... I think that this is the problem

**Comment by brenopolanski** [comment]
here i get the token and put in **app**: https://github.com/brenopolanski/coffee-club/blob/master/controllers/auth.js#L17

after...

is used in **github-api**: https://github.com/brenopolanski/coffee-club/blob/master/controllers/home.js#L15
